{
 "title": "Loki v2 Events Dashboard for Kubernetes",
 "description": "Kubernetes Events Dashboard  by CloudXiaobai",
 "tags": [
  "loki",
  "kubernetes",
  "events"
 ],
 "time": { "from": "now-30m", "to": "now" },
 "panels": [
  {
   "title": "Kubernetes event",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum by (type) (count_over_time({job=\"monitoring/event-exporter\"}| json |  __error__=\"\" [$__interval]))",
     "legendFormat": "{{type}}"
    }
   ]
  },
  {
   "title": "Warnning",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum(count_over_time({job=\"monitoring/event-exporter\"}| json | type = \"Warning\" | __error__=\"\" [$__interval]))",
     "legendFormat": "Warning"
    }
   ]
  },
  { "title": "Kubernetes Events Latest 24h", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 8 } },
  {
   "type": "stat",
   "gridPos": { "h": 4, "w": 4, "x": 0, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "sum" ] } },
   "targets": [
    {
     "expr": "sum(count_over_time({job=\"monitoring/event-exporter\"}|= \"Error: ImagePullBackOff\" | json | reason = \"Failed\"  | line_format \"{{ .message }}\"| __error__=\"\"[$__interval]))",
     "legendFormat": "Mirror pulse failure"
    }
   ]
  },
  {
   "type": "stat",
   "gridPos": { "h": 4, "w": 4, "x": 4, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "sum" ] } },
   "targets": [
    {
     "expr": "sum(count_over_time({job=\"monitoring/event-exporter\"}| json | reason = \"FailedScheduling\"| __error__=\"\"[$__interval]))",
     "legendFormat": "Failure"
    }
   ]
  },
  {
   "type": "stat",
   "gridPos": { "h": 4, "w": 4, "x": 8, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "sum" ] } },
   "targets": [
    {
     "expr": "sum(count_over_time({job=\"monitoring/event-exporter\"}| json | reason = \"SuccessfulDelete\"| __error__=\"\"[$__interval]))",
     "legendFormat": "Resource successfully delete"
    }
   ]
  },
  {
   "type": "stat",
   "gridPos": { "h": 4, "w": 4, "x": 12, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "sum" ] } },
   "targets": [
    {
     "expr": "sum(count_over_time({job=\"monitoring/event-exporter\"} |= \"failed liveness probe\"| json | reason = \"Killing\"| __error__=\"\"[$__interval]))",
     "legendFormat": "Probe failure"
    }
   ]
  },
  {
   "type": "stat",
   "gridPos": { "h": 4, "w": 4, "x": 16, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "sum" ] } },
   "targets": [
    {
     "expr": "sum(count_over_time({job=\"monitoring/event-exporter\"}|= \"Marking for deletion Pod\"| json | reason = \"ConntrackFull\"| __error__=\"\"[$__interval]))",
     "legendFormat": "ConntrackFull"
    }
   ]
  },
  {
   "type": "stat",
   "gridPos": { "h": 4, "w": 4, "x": 20, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "sum" ] } },
   "targets": [
    {
     "expr": "sum(count_over_time({job=\"monitoring/event-exporter\"}| json | reason = \"Rebooted\"| __error__=\"\"[$__interval]))",
     "legendFormat": "Node restart"
    }
   ]
  },
  {
   "type": "stat",
   "gridPos": { "h": 4, "w": 4, "x": 0, "y": 13 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "sum" ] } },
   "targets": [
    {
     "expr": "sum(count_over_time({job=\"monitoring/event-exporter\"} | json | reason = \"OOMKilling\"| __error__=\"\"[$__interval]))",
     "legendFormat": "Container OOM"
    }
   ]
  },
  {
   "type": "stat",
   "gridPos": { "h": 4, "w": 4, "x": 4, "y": 13 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "sum" ] } },
   "targets": [
    {
     "expr": "sum(count_over_time({job=\"monitoring/event-exporter\"}| json | reason = \"DockerHung\"| __error__=\"\"[$__interval]))",
     "legendFormat": "DockerHung"
    }
   ]
  },
  {
   "type": "stat",
   "gridPos": { "h": 4, "w": 4, "x": 8, "y": 13 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "sum" ] } },
   "targets": [
    {
     "expr": "sum(count_over_time({job=\"monitoring/event-exporter\"}| json | reason = \"BackOff\"| __error__=\"\"[$__interval]))",
     "legendFormat": " Container Crash"
    }
   ]
  },
  {
   "type": "stat",
   "gridPos": { "h": 4, "w": 4, "x": 12, "y": 13 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "sum" ] } },
   "targets": [
    {
     "expr": "sum(count_over_time({job=\"monitoring/event-exporter\"}| json | reason = \"FailedMount\"| __error__=\"\"[$__interval]))",
     "legendFormat": "Volume mount failed"
    }
   ]
  },
  {
   "type": "stat",
   "gridPos": { "h": 4, "w": 4, "x": 16, "y": 13 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "sum" ] } },
   "targets": [
    {
     "expr": "sum(count_over_time({job=\"monitoring/event-exporter\"}| json | reason = \"SystemOOM\"| __error__=\"\"[$__interval]))",
     "legendFormat": "Node OOM"
    }
   ]
  },
  {
   "type": "stat",
   "gridPos": { "h": 4, "w": 4, "x": 20, "y": 13 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "sum" ] } },
   "targets": [
    {
     "expr": "sum(count_over_time({job=\"monitoring/event-exporter\"}|= \"Marking for deletion Pod\"| json | reason = \"TaintManagerEviction\"| __error__=\"\"[$__interval]))",
     "legendFormat": " Container  Eviction"
    }
   ]
  },
  { "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 17 } },
  {
   "title": "TOP 10  Kubernetes Events",
   "type": "table",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 18 },
   "targets": [
    {
     "expr": "topk(10,sum by (reason) (count_over_time({job=\"monitoring/event-exporter\"}| json | __error__=\"\"[$__interval])))",
     "legendFormat": "{{reason}}"
    }
   ]
  },
  {
   "title": "Event source",
   "type": "grafana-piechart-panel",
   "gridPos": { "h": 7, "w": 6, "x": 12, "y": 18 },
   "format": "short",
   "valueName": "total",
   "targets": [
    {
     "expr": "sum(count_over_time({job=\"monitoring/event-exporter\"}| json| __error__=\"\"[$__interval])) by (source_component)",
     "legendFormat": "{{source_component}}"
    }
   ]
  },
  {
   "title": "Event type",
   "type": "grafana-piechart-panel",
   "gridPos": { "h": 7, "w": 6, "x": 18, "y": 18 },
   "format": "short",
   "valueName": "total",
   "targets": [
    {
     "expr": "sum(count_over_time({job=\"monitoring/event-exporter\"}| json| __error__=\"\"[$__interval])) by (involvedObject_kind)",
     "legendFormat": "{{involvedObject_kind}}"
    }
   ]
  },
  {
   "title": "Container evicted list",
   "type": "table",
   "gridPos": { "h": 11, "w": 24, "x": 0, "y": 25 },
   "targets": [
    {
     "expr": "sum by (firstTimestamp,message) (count_over_time({job=\"monitoring/event-exporter\"}|= \"Marking for deletion Pod\"| json | reason = \"TaintManagerEviction\"| __error__=\"\"[$__interval]))",
     "legendFormat": "{{firstTimestamp}}    发生事件 {{message}}"
    }
   ]
  }
 ]
}